//! Two-mode formalizer portfolio: a FAST non-CoT pass and a PRECISE CoT pass,
//! run in escalation order so the expensive chain-of-thought formalizer is only
//! paid for when the cheap one fails.
//!
//! Where [`crate::formalize_portfolio`](super::formalize_portfolio) fans ONE
//! informal statement out into many competing renderings and screens them ALL,
//! this module is the COST layer over that idea (DeepSeek-Prover-V2 / Kimina
//! style): a fast, non-chain-of-thought formalizer produces a first candidate
//! slate cheaply; only if none of those pass the screen do we ESCALATE to the
//! slow, chain-of-thought formalizer. The winning mode and the full attempt log
//! are reported so the escalation decision is auditable.
//!
//! Both seams are INJECTED and deterministic:
//! * the [`ModeFormalizer`] produces candidate Lean statements FOR A GIVEN MODE
//!   (in production: a small/greedy sample for [`FormalizeMode::FastNoCot`], a
//!   CoT best-of-N for [`FormalizeMode::PreciseCot`]; in tests: a mock);
//! * the validator is the portfolio's EXISTING screen — the same
//!   [`StatementScreen`] trait — so "faithful / well-formed" means exactly what
//!   it means in [`formalize_portfolio`](super::formalize_portfolio::formalize_portfolio).
//!
//! Nothing here reads wall-clock time or an unseeded RNG: a run is a pure
//! function of `(informal, config, seams)`.

use super::formalize_portfolio::{ScreenResult, StatementScreen};
use serde::{Deserialize, Serialize};

/// Which formalizer pass produced a candidate, with its cost/latency metadata.
///
/// The two variants are ordered by escalation preference: [`FormalizeMode::FastNoCot`]
/// is tried first and, being cheaper, is preferred on ties by [`select_best`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FormalizeMode {
    /// A cheap, non-chain-of-thought formalization pass (greedy / small sample).
    FastNoCot,
    /// A precise chain-of-thought formalization pass (CoT best-of-N) — used only
    /// on escalation, when the fast pass yields nothing that passes the screen.
    PreciseCot,
}

impl FormalizeMode {
    /// Relative COST budget units this mode consumes (the fast pass is the unit;
    /// the CoT pass is materially dearer). Used for budget accounting and as the
    /// tie-breaker in [`select_best`] (cheaper wins).
    pub const fn cost(self) -> u32 {
        match self {
            FormalizeMode::FastNoCot => 1,
            FormalizeMode::PreciseCot => 5,
        }
    }

    /// Nominal latency in milliseconds — advisory metadata for schedulers, NOT a
    /// value read from any clock at run time.
    pub const fn latency_ms(self) -> u32 {
        match self {
            FormalizeMode::FastNoCot => 200,
            FormalizeMode::PreciseCot => 3_000,
        }
    }

    /// Whether this mode reasons with an explicit chain of thought.
    pub const fn uses_cot(self) -> bool {
        matches!(self, FormalizeMode::PreciseCot)
    }

    /// Escalation order: the mode tried immediately after this one, if any.
    /// `FastNoCot` escalates to `PreciseCot`; `PreciseCot` is terminal.
    pub const fn escalates_to(self) -> Option<FormalizeMode> {
        match self {
            FormalizeMode::FastNoCot => Some(FormalizeMode::PreciseCot),
            FormalizeMode::PreciseCot => None,
        }
    }

    /// Human-readable label for logs.
    pub const fn label(self) -> &'static str {
        match self {
            FormalizeMode::FastNoCot => "fast-no-cot",
            FormalizeMode::PreciseCot => "precise-cot",
        }
    }
}

/// Produce candidate FORMAL statements for one informal statement IN A GIVEN MODE.
///
/// The `seed` is threaded so a run is reproducible: production samples the
/// mode's model deterministically from it; the test mock derives its candidates
/// from it. Implementations MUST NOT read wall-clock time or an unseeded RNG.
pub trait ModeFormalizer {
    /// Candidate formal renderings of `informal`, generated by `mode` under `seed`.
    fn formalize_mode(&self, mode: FormalizeMode, informal: &str, seed: u64) -> Vec<String>;
}

/// One screened candidate, tagged with the mode that produced it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ModeCandidate {
    /// The formal statement source (trimmed).
    pub formal: String,
    /// The mode that produced this candidate.
    pub mode: FormalizeMode,
    /// Well-formedness verdict from the injected screen.
    pub well_formed: bool,
    /// Triviality verdict from the injected screen.
    pub trivial: bool,
    /// The screen's rationale.
    pub note: String,
}

impl ModeCandidate {
    /// A candidate is VALID (an acceptable formalization) iff the screen judged
    /// it well-formed AND non-trivial — the same bar
    /// [`formalize_portfolio`](super::formalize_portfolio::formalize_portfolio)
    /// uses to recommend.
    pub fn valid(&self) -> bool {
        self.well_formed && !self.trivial
    }
}

/// The record of one mode's pass: every candidate it produced (screened) and
/// whether the pass yielded anything valid.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ModeAttempt {
    /// The mode that ran.
    pub mode: FormalizeMode,
    /// Every candidate the mode produced, screened, in generation order.
    pub candidates: Vec<ModeCandidate>,
    /// Whether at least one candidate passed the screen.
    pub produced_valid: bool,
    /// Why this pass ran / what happened (audit trail).
    pub note: String,
}

/// The outcome of a two-mode run: the chosen formalization (if any), which mode
/// won, whether escalation happened, and the full per-mode attempt log.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TwoModeOutcome {
    /// The informal statement that was formalized.
    pub informal: String,
    /// The chosen candidate — the best VALID one across the modes that ran, or,
    /// if none was valid, the best-scoring candidate seen (advisory). `None` only
    /// when no mode produced any candidate at all.
    pub chosen: Option<ModeCandidate>,
    /// The mode that produced [`chosen`](Self::chosen), if any.
    pub winning_mode: Option<FormalizeMode>,
    /// Whether the precise CoT pass was invoked (fast pass failed AND budget
    /// permitted the escalation).
    pub escalated: bool,
    /// Total cost units spent across the passes that actually ran.
    pub spent: u32,
    /// The per-mode attempt log, in run order (fast first).
    pub log: Vec<ModeAttempt>,
}

/// Knobs for a two-mode run.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TwoModeConfig {
    /// Seed threaded into [`ModeFormalizer::formalize_mode`] for reproducibility.
    pub seed: u64,
    /// Total cost budget (in [`FormalizeMode::cost`] units). The precise pass is
    /// only invoked when the REMAINING budget covers its cost; a budget that only
    /// affords the fast pass forbids escalation.
    pub budget: u32,
    /// Upper bound on candidates screened per mode (a runaway generator cannot
    /// blow up the screen budget).
    pub max_candidates_per_mode: usize,
}

impl Default for TwoModeConfig {
    fn default() -> Self {
        // Default budget affords both passes (1 + 5).
        TwoModeConfig {
            seed: 0,
            budget: 6,
            max_candidates_per_mode: 8,
        }
    }
}

/// The two-mode escalation portfolio: fast-first, precise-on-failure.
pub struct TwoModePortfolio<'a> {
    formalizer: &'a dyn ModeFormalizer,
    screen: &'a dyn StatementScreen,
}

impl<'a> TwoModePortfolio<'a> {
    /// Wire the (mode-aware) formalizer seam and the validator screen seam.
    pub fn new(formalizer: &'a dyn ModeFormalizer, screen: &'a dyn StatementScreen) -> Self {
        TwoModePortfolio { formalizer, screen }
    }

    /// Run the fast pass; escalate to the precise pass ONLY when the fast pass
    /// produced no valid candidate and the budget still affords the precise cost.
    ///
    /// Returns the chosen formalization (best valid across the passes that ran,
    /// else the best-scoring candidate), the winning mode, whether escalation
    /// happened, the total spend, and the full attempt log.
    pub fn run(&self, informal: &str, config: &TwoModeConfig) -> TwoModeOutcome {
        let mut log: Vec<ModeAttempt> = Vec::new();
        let mut spent: u32 = 0;

        // --- Fast pass (always runs first). ---
        let fast = self.run_mode(
            FormalizeMode::FastNoCot,
            informal,
            config,
            "primary fast non-CoT pass",
        );
        spent += FormalizeMode::FastNoCot.cost();
        let fast_valid = fast.produced_valid;
        log.push(fast);

        // Fast succeeded → do NOT invoke the precise pass (cost saved).
        if fast_valid {
            return self.finish(informal, log, spent, false);
        }

        // --- Escalation gate: only when budget still covers the precise pass. ---
        let precise_cost = FormalizeMode::PreciseCot.cost();
        let mut escalated = false;
        if spent + precise_cost <= config.budget {
            let precise = self.run_mode(
                FormalizeMode::PreciseCot,
                informal,
                config,
                "escalation: fast pass produced no valid candidate",
            );
            spent += precise_cost;
            escalated = true;
            log.push(precise);
        } else {
            // Budget forbids escalation; record why, mode not run.
            log.push(ModeAttempt {
                mode: FormalizeMode::PreciseCot,
                candidates: Vec::new(),
                produced_valid: false,
                note: format!(
                    "escalation skipped: remaining budget {} < precise cost {precise_cost}",
                    config.budget.saturating_sub(spent)
                ),
            });
        }

        self.finish(informal, log, spent, escalated)
    }

    /// Generate (capped), screen, and tag candidates for one mode.
    fn run_mode(
        &self,
        mode: FormalizeMode,
        informal: &str,
        config: &TwoModeConfig,
        note: &str,
    ) -> ModeAttempt {
        let raw = self.formalizer.formalize_mode(mode, informal, config.seed);
        let mut candidates: Vec<ModeCandidate> = Vec::new();
        for formal in raw.into_iter().take(config.max_candidates_per_mode) {
            let formal = formal.trim().to_string();
            if formal.is_empty() {
                continue;
            }
            let ScreenResult {
                well_formed,
                trivial,
                note: screen_note,
            } = self.screen.screen(&formal);
            candidates.push(ModeCandidate {
                formal,
                mode,
                well_formed,
                trivial,
                note: screen_note,
            });
        }
        let produced_valid = candidates.iter().any(ModeCandidate::valid);
        ModeAttempt {
            mode,
            candidates,
            produced_valid,
            note: note.to_string(),
        }
    }

    /// Assemble the outcome: pick the best candidate across every pass that ran.
    fn finish(
        &self,
        informal: &str,
        log: Vec<ModeAttempt>,
        spent: u32,
        escalated: bool,
    ) -> TwoModeOutcome {
        let all: Vec<ModeCandidate> = log
            .iter()
            .flat_map(|a| a.candidates.iter().cloned())
            .collect();
        let chosen = select_best(&all).map(|i| all[i].clone());
        let winning_mode = chosen.as_ref().map(|c| c.mode);
        TwoModeOutcome {
            informal: informal.to_string(),
            chosen,
            winning_mode,
            escalated,
            spent,
            log,
        }
    }
}

/// Choose the best candidate: VALID candidates always beat invalid ones, and
/// among equals the cheaper mode wins (so a valid fast rendering is preferred to
/// a valid precise one, and a valid fast rendering is preferred to an INVALID
/// precise one). Returns the index of the winner, or `None` for an empty slice.
///
/// The scan is stable — on a full tie the first-seen (earliest, hence
/// fast-before-precise by run order) candidate is kept — so the result is
/// deterministic.
pub fn select_best(candidates: &[ModeCandidate]) -> Option<usize> {
    let mut best: Option<usize> = None;
    for (i, c) in candidates.iter().enumerate() {
        match best {
            None => best = Some(i),
            Some(b) => {
                if candidate_score(c) > candidate_score(&candidates[b]) {
                    best = Some(i);
                }
            }
        }
    }
    best
}

/// Ranking key for [`select_best`]: `(valid, -cost)` — validity dominates, then
/// lower cost (cheaper mode) is preferred. Strictly-greater comparison keeps the
/// first-seen candidate on ties.
fn candidate_score(c: &ModeCandidate) -> (bool, i64) {
    (c.valid(), -(c.mode.cost() as i64))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A mock screen (mirrors the portfolio's marker screen): well-formed iff it
    /// carries a turnstile, trivial iff its conclusion is literally `True`.
    struct MarkerScreen;
    impl StatementScreen for MarkerScreen {
        fn screen(&self, formal: &str) -> ScreenResult {
            let well_formed = formal.contains('⊢') || formal.contains("|-");
            let trivial = formal.trim_end().ends_with("True");
            ScreenResult {
                well_formed,
                trivial,
                note: format!("wf={well_formed} trivial={trivial}"),
            }
        }
    }

    /// Fast pass ALWAYS yields a valid rendering; precise would too. Used to prove
    /// the precise pass is not even consulted when fast succeeds.
    struct FastSucceeds;
    impl ModeFormalizer for FastSucceeds {
        fn formalize_mode(&self, mode: FormalizeMode, informal: &str, _seed: u64) -> Vec<String> {
            match mode {
                FormalizeMode::FastNoCot => vec![format!("Hf ⊢ {informal}")],
                // If this ever runs, it is distinguishable in the log.
                FormalizeMode::PreciseCot => vec![format!("Hp ⊢ {informal}")],
            }
        }
    }

    /// Fast pass yields only INVALID renderings (ill-formed + trivial); precise
    /// yields a valid one. Used to prove escalation.
    struct FastFailsPreciseSaves;
    impl ModeFormalizer for FastFailsPreciseSaves {
        fn formalize_mode(&self, mode: FormalizeMode, informal: &str, _seed: u64) -> Vec<String> {
            match mode {
                FormalizeMode::FastNoCot => {
                    vec!["garbage".to_string(), "⊢ True".to_string()]
                }
                FormalizeMode::PreciseCot => vec![format!("Hp ⊢ {informal}")],
            }
        }
    }

    /// A seed-dependent generator (deterministic, no RNG) to prove reproducibility
    /// and that the seed is threaded through both modes.
    struct SeedEcho;
    impl ModeFormalizer for SeedEcho {
        fn formalize_mode(&self, mode: FormalizeMode, informal: &str, seed: u64) -> Vec<String> {
            match mode {
                FormalizeMode::FastNoCot => vec!["garbage".to_string()],
                FormalizeMode::PreciseCot => vec![format!("H{seed} ⊢ {informal}")],
            }
        }
    }

    fn portfolio<'a>(
        f: &'a dyn ModeFormalizer,
        s: &'a dyn StatementScreen,
    ) -> TwoModePortfolio<'a> {
        TwoModePortfolio::new(f, s)
    }

    #[test]
    fn valid_fast_does_not_invoke_precise() {
        let screen = MarkerScreen;
        let f = FastSucceeds;
        let out = portfolio(&f, &screen).run("phi", &TwoModeConfig::default());

        assert!(
            !out.escalated,
            "precise pass must not run when fast succeeds"
        );
        assert_eq!(out.winning_mode, Some(FormalizeMode::FastNoCot));
        assert_eq!(
            out.spent,
            FormalizeMode::FastNoCot.cost(),
            "only fast cost paid"
        );
        // Only the fast pass appears in the log (precise never consulted).
        assert_eq!(out.log.len(), 1);
        assert_eq!(out.log[0].mode, FormalizeMode::FastNoCot);
        let chosen = out.chosen.expect("a valid fast candidate");
        assert!(chosen.valid());
        assert_eq!(chosen.formal, "Hf ⊢ phi");
    }

    #[test]
    fn fast_failure_escalates_to_precise_and_returns_it() {
        let screen = MarkerScreen;
        let f = FastFailsPreciseSaves;
        let out = portfolio(&f, &screen).run("phi", &TwoModeConfig::default());

        assert!(
            out.escalated,
            "must escalate when fast produces nothing valid"
        );
        assert_eq!(out.winning_mode, Some(FormalizeMode::PreciseCot));
        assert_eq!(
            out.spent,
            FormalizeMode::FastNoCot.cost() + FormalizeMode::PreciseCot.cost(),
            "both passes paid"
        );
        let chosen = out.chosen.expect("precise saved the run");
        assert!(chosen.valid());
        assert_eq!(chosen.mode, FormalizeMode::PreciseCot);
        assert_eq!(chosen.formal, "Hp ⊢ phi");
    }

    #[test]
    fn attempt_log_records_the_escalation() {
        let screen = MarkerScreen;
        let f = FastFailsPreciseSaves;
        let out = portfolio(&f, &screen).run("phi", &TwoModeConfig::default());

        assert_eq!(out.log.len(), 2, "both passes are logged");
        assert_eq!(out.log[0].mode, FormalizeMode::FastNoCot);
        assert!(!out.log[0].produced_valid, "fast produced nothing valid");
        assert_eq!(out.log[1].mode, FormalizeMode::PreciseCot);
        assert!(
            out.log[1].produced_valid,
            "precise produced a valid candidate"
        );
        assert!(
            out.log[1].note.contains("escalation"),
            "the precise attempt records WHY it ran, got {:?}",
            out.log[1].note
        );
    }

    #[test]
    fn budget_forbids_escalation_when_it_cannot_afford_precise() {
        let screen = MarkerScreen;
        let f = FastFailsPreciseSaves;
        // Budget only affords the fast pass (cost 1) — no room for precise (5).
        let cfg = TwoModeConfig {
            seed: 0,
            budget: FormalizeMode::FastNoCot.cost(),
            max_candidates_per_mode: 8,
        };
        let out = portfolio(&f, &screen).run("phi", &cfg);

        assert!(!out.escalated, "escalation must be gated by budget");
        assert_eq!(out.spent, FormalizeMode::FastNoCot.cost());
        // Precise is logged as SKIPPED (not run), with an empty candidate set.
        assert_eq!(out.log.len(), 2);
        assert!(out.log[1].candidates.is_empty(), "precise did not run");
        assert!(out.log[1].note.contains("skipped"));
        // No valid candidate anywhere, so `chosen` is the best (invalid) fast one.
        let chosen = out.chosen.expect("a candidate is still surfaced");
        assert!(!chosen.valid());
        assert_eq!(chosen.mode, FormalizeMode::FastNoCot);
    }

    #[test]
    fn select_best_prefers_valid_fast_over_invalid_precise() {
        let valid_fast = ModeCandidate {
            formal: "Hf ⊢ g".to_string(),
            mode: FormalizeMode::FastNoCot,
            well_formed: true,
            trivial: false,
            note: String::new(),
        };
        let invalid_precise = ModeCandidate {
            formal: "garbage".to_string(),
            mode: FormalizeMode::PreciseCot,
            well_formed: false,
            trivial: false,
            note: String::new(),
        };
        // Order does not matter: validity dominates cost.
        assert_eq!(
            select_best(&[valid_fast.clone(), invalid_precise.clone()]),
            Some(0)
        );
        assert_eq!(select_best(&[invalid_precise, valid_fast]), Some(1));
    }

    #[test]
    fn select_best_prefers_cheaper_mode_among_valid() {
        let valid_precise = ModeCandidate {
            formal: "Hp ⊢ g".to_string(),
            mode: FormalizeMode::PreciseCot,
            well_formed: true,
            trivial: false,
            note: String::new(),
        };
        let valid_fast = ModeCandidate {
            formal: "Hf ⊢ g".to_string(),
            mode: FormalizeMode::FastNoCot,
            well_formed: true,
            trivial: false,
            note: String::new(),
        };
        // Fast is cheaper → preferred among two valid candidates, regardless of order.
        assert_eq!(
            select_best(&[valid_precise.clone(), valid_fast.clone()]),
            Some(1)
        );
        assert_eq!(select_best(&[valid_fast, valid_precise]), Some(0));
        assert_eq!(select_best(&[]), None);
    }

    #[test]
    fn run_is_deterministic_and_threads_the_seed() {
        let screen = MarkerScreen;
        let f = SeedEcho;
        let cfg7 = TwoModeConfig {
            seed: 7,
            budget: 6,
            max_candidates_per_mode: 8,
        };
        let a = portfolio(&f, &screen).run("phi", &cfg7);
        let b = portfolio(&f, &screen).run("phi", &cfg7);
        assert_eq!(a, b, "same seed and inputs must yield an identical outcome");

        // A different seed threads through to the precise candidate text.
        let cfg9 = TwoModeConfig {
            seed: 9,
            budget: 6,
            max_candidates_per_mode: 8,
        };
        let c = portfolio(&f, &screen).run("phi", &cfg9);
        assert_ne!(a.chosen, c.chosen, "distinct seeds must diverge");
        assert_eq!(a.chosen.unwrap().formal, "H7 ⊢ phi");
        assert_eq!(c.chosen.unwrap().formal, "H9 ⊢ phi");
    }

    #[test]
    fn mode_metadata_orders_cost_latency_and_cot() {
        assert!(FormalizeMode::FastNoCot.cost() < FormalizeMode::PreciseCot.cost());
        assert!(FormalizeMode::FastNoCot.latency_ms() < FormalizeMode::PreciseCot.latency_ms());
        assert!(!FormalizeMode::FastNoCot.uses_cot());
        assert!(FormalizeMode::PreciseCot.uses_cot());
        assert_eq!(
            FormalizeMode::FastNoCot.escalates_to(),
            Some(FormalizeMode::PreciseCot)
        );
        assert_eq!(FormalizeMode::PreciseCot.escalates_to(), None);
    }
}
