#!/usr/bin/env bash
# Enable a REAL LLM for Theoremata generation (LiteLLM-backed).
# Usage:
#   source scripts/use-model.sh
#   export THEOREMATA_MODEL=anthropic/claude-sonnet-5      # any LiteLLM model id
#   export ANTHROPIC_API_KEY=sk-...                        # the matching provider key
#   cargo run -- formal-prove lean "your statement"        # now generated by the LLM
#
# Run the CLI from the repo root (the command globs components/*/python).
# Unset THEOREMATA_MODEL_COMMAND (or use THEOREMATA_MODEL_MOCK=1) to go back offline.
export THEOREMATA_MODEL_COMMAND='${THEOREMATA_PYTHON:-python} -E -c "import sys,glob,os;[sys.path.insert(0,os.path.abspath(p)) for p in glob.glob('"'"'components/*/python'"'"')];from theoremata_tools.model_provider import main;main()"'
echo "THEOREMATA_MODEL_COMMAND set. Now export THEOREMATA_MODEL=<litellm-id> and your provider API key, then run the CLI from the repo root."
